#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

hello_msg='Hello, World!'

hello() {
  echo $hello_msg
}

ignored_fuction ()  {
  # this function name will be ignored by autocompletion because of space between function name and curly brackets
  echo 'bye-bye.'
}

bye() {
  ignored_fuction
}

while [ $# != 0 ]; do
  if [ "$(type -t $1)" == 'function' ]; then
    $1 
  else
    exit 1
  fi 
  shift
done
